# Generated by Django 3.2.7 on 2021-10-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
