# Generated by Django 3.2.7 on 2021-10-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0002_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
